# 项目相关配置
ruoyi:
  #名称
  name: RuoYi
  #版本
  version: 2.4.0
  #版权年份
  copyrightYear: 2019
  #头像上传路径
  profile: /root/profile/
  imagePath: /root/imagePath/
  # 获取ip地址开关
  addressEnabled: false
#开发环境配置
server:
  #服务端口
  port: 443
  ssl:
    key-store: /root/quxiangwu.jks
    key-alias: alias
    enabled: true
    key-store-password: 2iuj3u0Y
    key-store-type: JKS
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
#日志配置
logging:
  level:
    com.ruoyi: WARN
    org.springframework: WARN
    org.spring.springboot.dao: WARN
