server:
  port: 8080
logging:
  config: classpath:logback-dev.xml
# 项目相关配置
ruoyi:
  #名称
  name: RuoYi
  #版本
  version: 2.4.0
  #版权年份
  copyrightYear: 2019
  #头像上传路径
  profile: /Users/zhouwenyang/Desktop/test
  imagePath: /Users/zhouwenyang/Desktop/test
  # 获取ip地址开关
  addressEnabled: false