#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
#Spring配置
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid,dev
  #文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  devtools:
    restart:
      #热部署开关
      enabled: true
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql 
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /unauth
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
# 代码生成
gen: 
  # 作者
  author: ruoyi
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.ruoyi.project.module
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_
wechat:
  appid: wxd143adf9bead318d
  secret: 8fdc195bf1ccd41f7a5150b3fca6740b
alipay:
  appId: 2019032363645373
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCy1DDWKqotGQ8MbhrjchhNse4lB/Dif8lE09uZ5lOfgM9CYETpabhUOvtdHXJ+SqxxHrBX/fOsXdjqywpUQfEMRd7XkKpCAzDaReQHoCionqsWudh54Jxwr2lTIQOYjf5hUkECQFVaYgzCa0r1LBn/JtWGg5EzXmBVSauIFPo8oXWp8zmc5wZvCLDIK8o73zlyMVfYejWRXO7+XfqBYwzTd3Axb0r8Kip7v+kWXHRRV2bWJGSNGwo7tkLDf3/arCTV4Bez7zjl7G3Ne0uOL9HGz3C2N/JfMTLDun27SiHSs5lBKNOtIC7cgFusbsdZKXxakmhH+zHEI221JiuR/nrnAgMBAAECggEAdXrssmXI8mOZ/UKAK5eS28feeTlkSIhGgw7jH5GusgR/JE32N5kaXUt6QsvLoagQ7SeKFeRhpoTosia9HGlNoBBuuxLwpvlNqLdtfIz86PmD0CQ7UKX8YBL8kH4JzLjLuse8qWv2JrBvTXILBlH4qiSq9fmM9EA17RG+vGF7m0Ql1ey4zDHibBQo4E1yS8PcEmWP0P3giSXzdfbY3WDhrO3dJnDDDsOwl/T7XZrEq2+OdOZeIv7d7EE1Lflo4aVqks5CntLRiiqkhTR5dX+4Tytb51Fa+DVh82QKtc0ZdMLmb4fNLAg0t0ohSYXKiVnlBZ6IKnMx2tL1ftHinWQBoQKBgQDWWkWRO0j8suoUiLMKgOBpjD2CV1jWRMzT23kRIcddZirT4d9KN5harq6siloB8BUhkoZPCmWirQAyqBFCgoG5KSd87PQvjF+I/B7a6reJiPJ2aJn/w5VgiM+jbmWtWykApytF4Hamf0sX+ix0pGPqyQoCMNwJQDlZOrOyPf9UzwKBgQDVkv7yi+nMbnwfqgW/1IzpPRl7ogmXSugy2XuXO9msFh8WXnCigKA6i85rTY0/xCPNxSoeWaOxGmNtsMRzrECoTIuSpgf2BPYQHh5JyZOrs4+K0rqhLHm2wUMIGPkObx6lGPXbBwIfuqB91q2QrkCZ+qMoO+VNOdWBPobfRWCuaQKBgHPzMuyD0FB5i6v94jPNURdnOCKYk0KcxtvXPd8pkYmRaZth9IJWHoD3Ox+0W0nvD88wTpzU9/OOd6vvRB7hL8D0ZRrrpo9N9KPKFfq/uvaX8OhiXuN+bgBhIUi7wB6NUFm9E+hhqm0YMIvQ1VlnT3FCvLpAqdYLOrpsyaWiacr7AoGAJrix9HOdfe0CIBOJW1BEA/2J4zprlryEAMQhfjfhrSuNk1aoAS5k3nh+gkHbPBZpj2MR0dLatL9eC4Mi+v3d8yV9oKbthpM7sYxkXWhol5bEjZzLLXGM16+OYad1cEKBQdmWqZFJt0r00hvb+AE/wSsJ7b9+QVQc+4PEnDJN5xECgYA2cfRmPzyf0zFAr7Ogn98T1qapeVy5bDVXceVyOGw/M591HhiN6GX0ejmZ/rEEya1aNm8kXf+xS/K9Bv9FdTtmqZXNSdZOdv4VVv5C89sVYijKgLwVn2hRLG5azON6Rn92ey32UXdGJuNaI85Zhym1GAbZ00fOJOaniC/VR9+BUQ==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAstQw1iqqLRkPDG4a43IYTbHuJQfw4n/JRNPbmeZTn4DPQmBE6Wm4VDr7XR1yfkqscR6wV/3zrF3Y6ssKVEHxDEXe15CqQgMw2kXkB6AoqJ6rFrnYeeCccK9pUyEDmI3+YVJBAkBVWmIMwmtK9SwZ/ybVhoORM15gVUmriBT6PKF1qfM5nOcGbwiwyCvKO985cjFX2Ho1kVzu/l36gWMM03dwMW9K/Coqe7/pFlx0UVdm1iRkjRsKO7ZCw39/2qwk1eAXs+845extzXtLji/Rxs9wtjfyXzEyw7p9u0oh0rOZQSjTrSAu3IBbrG7HWSl8WpJoR/sxxCNttSYrkf565wIDAQAB